# Generated by Django 5.0.1 on 2024-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=14)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('date_cad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
