# Generated by Django 4.2.9 on 2024-01-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=14)),
                ('turno', models.CharField(choices=[('MA', 'Manha'), ('TA', 'Tarde'), ('NO', 'Noite')], max_length=3)),
                ('dia_consulta', models.DateField()),
                ('horario_consulta', models.TimeField()),
            ],
        ),
    ]
